<!DOCTYPE html>
<html>
<head>
    <title>Ben and Margaret's Wedding</title>
    <link rel="stylesheet" type="text/css" href="css/stylesheet.css">
    <link rel="stylesheet" type="text/css" href="css/fontsheet.css">
    <!--<link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="css/bootstrap-theme.min.css">-->
    <script src="js/jquery-1.11.0.min.js" type="text/javascript"></script>
    <!--<script src="js/bootstrap.min.js" type="text/javascript"></script>-->
    <script src="js/plugin/session/jquery.session.js" type="text/javascript"></script>
</head>
<body>
<div id="ribbon">
<div id="body">
<div id="header" style="height:145px;width:100%;">
    <div id="menu" style="height:145px;width:100%;">
        <ul class="menu-flag">
            <li><a href="index.php"><span>About<br/>Us</a></span></li>
            <li><a href="meet_the_maids.php"><span>Meet the<br/>Maids</span></a></li>
            <li><a href="meet_the_men.php"><span>Meet the<br/>Men</span></a></li>
            <li><a href="hotel_info.php"><span>Hotel<br/>Info</a></span></li>
            <li><a href="lodge_info.php"><span>The Main<br/>Event</a></span></li>
        </ul>
    </div>
</div>
